# Generated by Django 3.1 on 2023-12-18 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('image_path', models.ImageField(upload_to='categoria/')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaSubcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('ruc_cedula', models.CharField(max_length=13)),
                ('razon_social', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('provincia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('state', models.CharField(blank=True, choices=[('Inactivo', 'Inactivo'), ('Pendiente', 'Pendiente'), ('Activo', 'Activo')], default='Pendiente', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorCategoriaSubcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriasubcategoria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image_path', models.ImageField(upload_to='proveedor/')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='categoriasubcategoria',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subcategoria'),
        ),
    ]
