# Generated by Django 4.2.9 on 2024-04-17 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_categoria_id_alter_categoriasubcategoria_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("provincia", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.provincia"
            ),
        ),
    ]
