# Generated by Django 4.2.9 on 2024-11-13 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_provincia_alter_proveedor_provincia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proveedor",
            name="provincia",
        ),
        migrations.CreateModel(
            name="ProveedorProvincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.proveedor"
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.provincia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnlaceProveedor",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("tipo_enlace", models.CharField(max_length=50)),
                ("enlace", models.CharField(max_length=500)),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.proveedor"
                    ),
                ),
            ],
        ),
    ]
