# Generated by Django 4.2.9 on 2024-11-14 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_proveedor_provincia_proveedorprovincia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedorprovincia",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provincia_name",
                to="core.provincia",
            ),
        ),
    ]
