# Generated by Django 4.2.9 on 2024-11-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_proveedorprovincia_provincia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provincia",
            name="provincia",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
