# Generated by Django 4.2.9 on 2024-11-19 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_provincia_provincia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriasubcategoria",
            name="subcategoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.subcategoria",
            ),
        ),
        migrations.AlterField(
            model_name="provincia",
            name="provincia",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
