# Generated by Django 4.2.9 on 2024-11-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_categoriasubcategoria_subcategoria_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enlaceproveedor",
            name="tipo_enlace",
        ),
        migrations.AddField(
            model_name="enlaceproveedor",
            name="linkType",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Facebook", "Facebook"),
                    ("Instagram", "Instagram"),
                    ("TikTok", "TikTok"),
                    ("X", "X"),
                    ("Otros", "Otros"),
                ],
                default="Otros",
                max_length=500,
            ),
        ),
    ]
