# Generated by ChatGPT

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_enlaceproveedor_tipo_enlace_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagenTemporalProveedor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False, unique=True)),
                ("image_path", models.ImageField(upload_to="proveedorTemporal/")),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.proveedor",
                    ),
                ),
            ],
        ),
    ]

